#!/bin/sh

pkill -x dmenu
xdotool search --class conky windowunmap %@
dmenu_run -l 20 \
	-w 200 \
	-y 0 \
	-x 55\
	-fn -lucy-tewi-medium-r-normal--11-90-75-75-p-58-iso10646-1 \
	-nb '#000000' \
	-nf '#dadada' \
	-sf '#dadada' \
	-sb '#5f87af' \
	-o 0.95 2>/dev/null
