#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X


bspc config border_width        2
bspc config top_padding         14 
bspc config window_gap          12
bspc config split_ratio         0.50
bspc config borderless_monocle  false
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#181512"
bspc config active_border_color "#504339"
bspc config focused_border_color "#817267"
bspc config presel_border_color "#AC4142"
bspc config urgent_border_color "#504339"
bspc config focused_locked_border_color "#8c644c"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.05


# Rules
bspc rule -a Chromium desktop=^2
bspc rule -a Screenkey manage=off

feh --bg-max ~/Desktop/Wallpaper.jpg
compton --config ~/.config/compton.conf &
#conky &
~/.config/bspwm/panel/panel &
